# Generated by Django 3.2.10 on 2021-12-23 03:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0074_remove_company_req'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legislation', '0171_auto_20211223_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='Started')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Finish date')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='Name')),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_company', to='company.company')),
            ],
            options={
                'verbose_name': 'ISO Product',
                'verbose_name_plural': 'ISO Products',
                'ordering': ['-finished'],
            },
        ),
        migrations.CreateModel(
            name='ISOStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(max_length=60000, null=True, verbose_name='Full description')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('changed', models.BooleanField(default=False, editable=False, verbose_name='Changed')),
                ('free', models.BooleanField(default=False, verbose_name='Show for free')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order for free')),
                ('orderfull', models.PositiveIntegerField(default=1, verbose_name='Order for full')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iss_location', to='legislation.location')),
            ],
            options={
                'verbose_name': 'ISO Standard',
                'verbose_name_plural': 'ISO Standards',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ISOStandardComply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=60000, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comply option',
                'verbose_name_plural': 'Comply option',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ISOStandardKeyPointResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, max_length=4000, null=True)),
                ('response', models.IntegerField(blank=True, choices=[(1, 'Full Compliance'), (0, 'No Compliance')], null=True)),
                ('ncnote', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ISO Standard key point response',
                'verbose_name_plural': 'ISO Standard key point responses',
            },
        ),
        migrations.CreateModel(
            name='ISOStandardNCResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identified', models.TextField(max_length=2000, null=True, verbose_name='Identified by')),
                ('assigned', models.TextField(max_length=2000, null=True, verbose_name='Assigned to')),
                ('containment', models.TextField(max_length=2000, null=True, verbose_name='Containment actions')),
                ('completion', models.TextField(max_length=2000, null=True, verbose_name='Completion date & by whom')),
                ('root', models.TextField(max_length=2000, null=True, verbose_name='Root cause')),
                ('corrective', models.TextField(max_length=2000, null=True, verbose_name='Actions to be taken')),
                ('cost', models.TextField(max_length=2000, null=True, verbose_name='Cost of nonconformance')),
                ('reviewed', models.TextField(max_length=2000, null=True, verbose_name='Reviewed and closed out by')),
                ('desc', models.TextField(max_length=2000, null=True, verbose_name='Description')),
                ('ncdesc', models.TextField(max_length=2000, null=True, verbose_name='NC description')),
                ('verified', models.BooleanField(default=False, editable=False, verbose_name='Verified')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=15, verbose_name='Priority')),
                ('completeddate', models.DateField(null=True, verbose_name='Completion date')),
                ('revieweddate', models.DateField(null=True, verbose_name='Review date')),
                ('no', models.PositiveIntegerField(default=1, verbose_name='No')),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nccompleted', to=settings.AUTH_USER_MODEL, verbose_name='Identified by')),
                ('identified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncidentified', to=settings.AUTH_USER_MODEL, verbose_name='Identified by')),
            ],
            options={
                'verbose_name': 'NC',
                'verbose_name_plural': 'NC',
                'ordering': ['started'],
            },
        ),
        migrations.CreateModel(
            name='ISOStandardOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=600, verbose_name='Option')),
                ('comply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iss_option_comply', to='legislation.isostandardcomply')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['option'],
            },
        ),
        migrations.CreateModel(
            name='ISOStandardResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('response', models.IntegerField(blank=True, choices=[(1, 'Full Compliance'), (0, 'No Compliance'), (2, 'Partial Compliance')], null=True)),
                ('pos', models.IntegerField(blank=True, editable=False, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('ncnote', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'No Compliance'), (2, 'Incomplete'), (3, 'Full Compliance')], default=0, editable=False)),
                ('isostandard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iss_response_standard', to='legislation.isostandard')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iss_response_product', to='legislation.isoproduct')),
                ('requirements', models.ManyToManyField(blank=True, to='legislation.ISOStandardOption')),
            ],
            options={
                'verbose_name': 'ISO Standard response',
                'verbose_name_plural': 'ISO Standard responses',
                'ordering': ['pos'],
                'unique_together': {('isostandard', 'product')},
            },
        ),
        migrations.CreateModel(
            name='NCOuterResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialrecord', models.BooleanField(default=False)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identified', models.TextField(max_length=2000, null=True, verbose_name='Identified by')),
                ('assigned', models.TextField(max_length=2000, null=True, verbose_name='Assigned to')),
                ('containment', models.TextField(max_length=2000, null=True, verbose_name='Containment actions')),
                ('completion', models.TextField(max_length=2000, null=True, verbose_name='Completion date & by whom')),
                ('root', models.TextField(max_length=2000, null=True, verbose_name='Root cause')),
                ('corrective', models.TextField(max_length=2000, null=True, verbose_name='Corrective actions')),
                ('cost', models.TextField(max_length=2000, null=True, verbose_name='Cost of nonconformance')),
                ('reviewed', models.TextField(max_length=2000, null=True, verbose_name='Reviewed and closed out by')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Description')),
                ('verified', models.BooleanField(default=False, editable=False, verbose_name='Verified')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=15, verbose_name='Priority')),
                ('completeddate', models.DateField(null=True, verbose_name='Completion date')),
                ('revieweddate', models.DateField(null=True, verbose_name='Review date')),
                ('no', models.PositiveIntegerField(default=1, verbose_name='No')),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncouterresponse_company', to='company.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncoutercompleted', to=settings.AUTH_USER_MODEL, verbose_name='Identified by')),
                ('identified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncouteridentified', to=settings.AUTH_USER_MODEL, verbose_name='Identified by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncouterreviewed', to=settings.AUTH_USER_MODEL, verbose_name='Identified by')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outersources', to='legislation.sourcenc')),
            ],
            options={
                'verbose_name': 'Outer NC',
                'verbose_name_plural': 'Outer NC',
                'ordering': ['started'],
            },
        ),
        migrations.CreateModel(
            name='NCOuterResponseStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identified', models.TextField(max_length=2000, null=True, verbose_name='Identified by')),
                ('assigned', models.TextField(max_length=2000, null=True, verbose_name='Assigned to')),
                ('containment', models.TextField(max_length=2000, null=True, verbose_name='Containment actions')),
                ('completion', models.TextField(max_length=2000, null=True, verbose_name='Completion date & by whom')),
                ('root', models.TextField(max_length=2000, null=True, verbose_name='Root cause')),
                ('corrective', models.TextField(max_length=2000, null=True, verbose_name='Corrective actions')),
                ('cost', models.TextField(max_length=2000, null=True, verbose_name='Cost of nonconformance')),
                ('reviewed', models.TextField(max_length=2000, null=True, verbose_name='Reviewed and closed out by')),
                ('desc', models.TextField(max_length=2000, null=True, verbose_name='Description')),
                ('verified', models.BooleanField(default=False, editable=False, verbose_name='Verified')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=15, verbose_name='Priority')),
                ('completeddate', models.DateField(null=True, verbose_name='Completion date')),
                ('revieweddate', models.DateField(null=True, verbose_name='Review date')),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncouterstatecompleted', to=settings.AUTH_USER_MODEL, verbose_name='Identified by')),
                ('identified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncouterstateidentified', to=settings.AUTH_USER_MODEL, verbose_name='Identified by')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ncresponsestates_product', to='legislation.isoproduct')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncouterstatereviewed', to=settings.AUTH_USER_MODEL, verbose_name='Identified by')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.sourcenc')),
            ],
            options={
                'verbose_name': 'State of Outer NC',
                'verbose_name_plural': 'State of Outer NC',
            },
        ),
        migrations.RemoveField(
            model_name='legislationnonconformanceresponse',
            name='assign',
        ),
        migrations.RemoveField(
            model_name='legislationnonconformanceresponse',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='legislationnonconformanceresponse',
            name='identified_by',
        ),
        migrations.RemoveField(
            model_name='legislationnonconformanceresponse',
            name='point',
        ),
        migrations.RemoveField(
            model_name='legislationnonconformanceresponse',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='legislationnonconformanceresponse',
            name='source',
        ),
        migrations.RemoveField(
            model_name='legislationnonconformanceresponse',
            name='topicreply',
        ),
        migrations.RemoveField(
            model_name='legislationposition',
            name='location',
        ),
        migrations.RemoveField(
            model_name='legislationposition',
            name='register',
        ),
        migrations.RemoveField(
            model_name='legislationposition',
            name='req',
        ),
        migrations.RemoveField(
            model_name='legislationposition',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='legislationspecquestion',
            name='position',
        ),
        migrations.RemoveField(
            model_name='legislationspecquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='legislationtopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='legislationtopic',
            name='location',
        ),
        migrations.RemoveField(
            model_name='legislationtopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='legislationtopiccomply',
            name='point',
        ),
        migrations.RemoveField(
            model_name='legislationtopicoption',
            name='comply',
        ),
        migrations.AlterUniqueTogether(
            name='legislationtopicskeypointresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='legislationtopicskeypointresponse',
            name='point',
        ),
        migrations.RemoveField(
            model_name='legislationtopicskeypointresponse',
            name='topicresponse',
        ),
        migrations.RemoveField(
            model_name='legislationtopicsresponse',
            name='legtopic',
        ),
        migrations.RemoveField(
            model_name='legislationtopicsresponse',
            name='position',
        ),
        migrations.RemoveField(
            model_name='legislationtopicsresponse',
            name='req',
        ),
        migrations.RemoveField(
            model_name='legislationtopicsresponse',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='nonconformanceouterresponse',
            name='assign',
        ),
        migrations.RemoveField(
            model_name='nonconformanceouterresponse',
            name='company',
        ),
        migrations.RemoveField(
            model_name='nonconformanceouterresponse',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='nonconformanceouterresponse',
            name='identified_by',
        ),
        migrations.RemoveField(
            model_name='nonconformanceouterresponse',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='nonconformanceouterresponse',
            name='source',
        ),
        migrations.RemoveField(
            model_name='nonconformanceouterresponsestates',
            name='assign',
        ),
        migrations.RemoveField(
            model_name='nonconformanceouterresponsestates',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='nonconformanceouterresponsestates',
            name='identified_by',
        ),
        migrations.RemoveField(
            model_name='nonconformanceouterresponsestates',
            name='legislation',
        ),
        migrations.RemoveField(
            model_name='nonconformanceouterresponsestates',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='nonconformanceouterresponsestates',
            name='source',
        ),
        migrations.RemoveField(
            model_name='question',
            name='legtopic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='register',
            name='company',
        ),
        migrations.AlterModelOptions(
            name='keypoint',
            options={'ordering': ['id'], 'verbose_name': 'Requirements', 'verbose_name_plural': 'Requirements'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['ord'], 'verbose_name': 'ISO Topic', 'verbose_name_plural': 'ISO Topics'},
        ),
        migrations.RemoveField(
            model_name='keypoint',
            name='legtopic',
        ),
        migrations.RemoveField(
            model_name='keypoint',
            name='req',
        ),
        migrations.AddField(
            model_name='keypoint',
            name='title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='keypoint',
            name='point',
            field=ckeditor.fields.RichTextField(max_length=60000, verbose_name='Requirement'),
        ),
        migrations.DeleteModel(
            name='LegislationDocument',
        ),
        migrations.DeleteModel(
            name='LegislationNonConformanceResponse',
        ),
        migrations.DeleteModel(
            name='LegislationPosition',
        ),
        migrations.DeleteModel(
            name='LegislationSpecQuestion',
        ),
        migrations.DeleteModel(
            name='LegislationTopic',
        ),
        migrations.DeleteModel(
            name='LegislationTopicComply',
        ),
        migrations.DeleteModel(
            name='LegislationTopicOption',
        ),
        migrations.DeleteModel(
            name='LegislationTopicsKeyPointResponse',
        ),
        migrations.DeleteModel(
            name='LegislationTopicsResponse',
        ),
        migrations.DeleteModel(
            name='NonConformanceOuterResponse',
        ),
        migrations.DeleteModel(
            name='NonConformanceOuterResponseStates',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.DeleteModel(
            name='Requirements',
        ),
        migrations.AddField(
            model_name='isostandardncresponse',
            name='issrepsonse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issresponse_ncresponse', to='legislation.isostandardresponse'),
        ),
        migrations.AddField(
            model_name='isostandardncresponse',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ncresponse_keypoint', to='legislation.keypoint'),
        ),
        migrations.AddField(
            model_name='isostandardncresponse',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncreviewed', to=settings.AUTH_USER_MODEL, verbose_name='Identified by'),
        ),
        migrations.AddField(
            model_name='isostandardncresponse',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.sourcenc'),
        ),
        migrations.AddField(
            model_name='isostandardkeypointresponse',
            name='issresponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issresponse_keypointresponse', to='legislation.isostandardresponse'),
        ),
        migrations.AddField(
            model_name='isostandardkeypointresponse',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issresponse_keypoint', to='legislation.keypoint'),
        ),
        migrations.AddField(
            model_name='isostandardcomply',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iss_comply_keypoint', to='legislation.keypoint'),
        ),
        migrations.AddField(
            model_name='isostandard',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iss_topic', to='legislation.topic'),
        ),
        migrations.AddField(
            model_name='keypoint',
            name='isostandard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iss_keypoint', to='legislation.isostandard'),
        ),
        migrations.AlterUniqueTogether(
            name='isostandardkeypointresponse',
            unique_together={('issresponse', 'point')},
        ),
    ]
