# Generated by Django 3.2.10 on 2021-12-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0172_auto_20211223_0353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Template',
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='disc_choice',
            field=models.BooleanField(default=False, verbose_name='Discount on two or more choices'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='disc_next_choice',
            field=models.BooleanField(default=False, verbose_name='Discount on every next choice'),
        ),
        migrations.AlterField(
            model_name='sourcenc',
            name='default',
            field=models.BooleanField(default=False, verbose_name='For ISO register'),
        ),
    ]
