# Generated by Django 3.2.10 on 2021-12-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0173_auto_20211223_0454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['title'], 'verbose_name': 'Template', 'verbose_name_plural': 'Template'},
        ),
    ]
