# Generated by Django 3.2.10 on 2021-12-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0175_documentfile_documentfolder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfolder',
            options={'ordering': ['name'], 'verbose_name': 'Management System', 'verbose_name_plural': 'Management System'},
        ),
    ]
