# Generated by Django 3.2.10 on 2021-12-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0176_alter_documentfolder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isostandardcomply',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keypoint_comply', to='legislation.keypoint'),
        ),
        migrations.AlterField(
            model_name='isostandardoption',
            name='comply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comply_option', to='legislation.isostandardcomply'),
        ),
    ]
