# Generated by Django 3.2.10 on 2021-12-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0177_auto_20211223_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.vatrate'),
        ),
    ]
