# Generated by Django 3.2.10 on 2021-12-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0178_topic_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, verbose_name='Name')),
                ('period', models.CharField(choices=[('annual', 'annual'), ('monthly', 'monthly')], default='monthly', max_length=10, verbose_name='Annual or Monthly')),
                ('user_count', models.IntegerField(verbose_name='User Count')),
                ('price', models.FloatField(verbose_name='Price')),
                ('del_price', models.FloatField(blank=True, null=True, verbose_name='del Price')),
                ('recommended', models.BooleanField(default=False, verbose_name='Is Recommended')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plan',
                'ordering': ['price'],
            },
        ),
    ]
