# Generated by Django 3.2.10 on 2021-12-24 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0179_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_document', to='legislation.isoproduct'),
        ),
    ]
