# Generated by Django 3.2.10 on 2021-12-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0180_documentfile_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfolder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_documentfolder', to='legislation.isoproduct'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_documentfile', to='legislation.isoproduct'),
        ),
    ]
