# Generated by Django 3.2.10 on 2021-12-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0181_auto_20211224_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfolder',
            name='usage',
            field=models.CharField(choices=[('Templates', 'Templates'), ('Evidence', 'Evidence'), ('', '')], default='', max_length=10, verbose_name='Annual or Monthly'),
        ),
    ]
