# Generated by Django 3.2.10 on 2021-12-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0182_documentfolder_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfolder',
            name='usage',
            field=models.CharField(choices=[('--', '--'), ('Templates', 'Templates'), ('Evidence', 'Evidence')], default='--', max_length=50, verbose_name='Usage Type'),
        ),
    ]
