# Generated by Django 3.2.10 on 2021-12-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0183_alter_documentfolder_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='standard_count',
            field=models.IntegerField(null=True, verbose_name='Standard Count'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('annual', 'annual'), ('monthly', 'monthly'), ('free', 'free')], default='free', max_length=50, verbose_name='Annual or Monthly'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user_count',
            field=models.IntegerField(null=True, verbose_name='User Count'),
        ),
    ]
