# Generated by Django 3.2.10 on 2021-12-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0184_auto_20211224_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='standard_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Standard Count'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user_count',
            field=models.IntegerField(default=0, null=True, verbose_name='User Count'),
        ),
    ]
