# Generated by Django 3.2.10 on 2021-12-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0185_auto_20211224_0855'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('period', 'free')), fields=('period',), name='unique_period_free'),
        ),
    ]
