# Generated by Django 3.2.10 on 2021-12-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0186_plan_unique_period_free'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plan',
            name='unique_period_free',
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('period', 'free')), fields=('id',), name='unique_period_free'),
        ),
    ]
