# Generated by Django 3.2.10 on 2021-12-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0187_auto_20211224_0919'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plan',
            name='unique_period_free',
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('period', 'free')), fields=('name',), name='unique_id_period'),
        ),
    ]
