# Generated by Django 3.2.10 on 2021-12-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0188_auto_20211224_0923'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plan',
            name='unique_id_period',
        ),
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('annual', 'annual'), ('monthly', 'monthly')], default='monthly', max_length=50, verbose_name='Annual or Monthly'),
        ),
    ]
