# Generated by Django 3.2.10 on 2021-12-23 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0073_auto_20211223_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='req',
        ),
    ]
