# Generated by Django 3.2.10 on 2021-12-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0172_auto_20211223_0353'),
        ('company', '0074_remove_company_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isostandard',
            field=models.ManyToManyField(blank=True, to='legislation.ISOStandard', verbose_name='ISO Standards'),
        ),
    ]
