# Generated by Django 3.2.10 on 2021-12-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0075_company_isostandard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_payment', to='company.company'),
        ),
        migrations.AlterField(
            model_name='paymentspositions',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_position', to='company.payments'),
        ),
    ]
